import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Footer, Navigations } from '@/components/sections/layout';
import { ConnectWithMe } from '@/components/widgets';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='bg-primary-default flex h-screen flex-col overflow-y-auto text-white'>
          <Navigations />
          <div>{children}</div>
          <ConnectWithMe />
          <Footer />
        </div>
      </body>
    </html>
  );
}
