import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';
import './globals.css';
import { Footer, Navigations } from '@/components/sections/layout';
import { ConnectWithMe } from '@/components/widgets';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Peter Okerulu's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${rubik.variable} antialiased`}>
        <div className='bg-primary-default flex h-screen flex-col overflow-y-auto text-white'>
          <Navigations />
          <div>{children}</div>
          <ConnectWithMe />
          <Footer />
        </div>
      </body>
    </html>
  );
}
